# Generated by Django 4.0.4 on 2022-04-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_local_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='local_evento',
            field=models.CharField(default=1, max_length=100, verbose_name='Local'),
            preserve_default=False,
        ),
    ]
