# Generated by Django 4.0.4 on 2022-04-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_evento_local_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='local_evento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local'),
        ),
    ]
